-- Semilla de public.leads — GENERADO, no editar a mano.
--
-- Origen: data/leads.json (opportunity-radar-valparaiso v1.0.0)
-- Regenerar: npm run data:seed
--
-- 15 prospectos reales de Región de Valparaíso, Chile. Los scores se
-- copian literalmente del documento canónico y no se recalculan aquí.

insert into public.leads (
  business_id,
  business_name,
  niche,
  subcategory,
  commune,
  address,
  latitude,
  longitude,
  website_url,
  has_website,
  website_classification,
  website_quality,
  instagram_url,
  facebook_url,
  social_only_presence,
  online_booking,
  online_ordering,
  online_menu,
  online_catalog,
  whatsapp_business,
  public_business_email,
  public_business_phone,
  rating,
  review_count,
  social_activity,
  multiple_locations,
  business_age_signal,
  digital_need_score,
  commercial_attractiveness_score,
  contactability_score,
  landing_fit_score,
  local_opportunity_score,
  priority_score,
  confidence_score,
  priority_tier,
  score_explanations,
  data_flags,
  source_primary,
  source_urls,
  retrieved_at,
  evidence_notes,
  demo_url
)
values
  ('b001', 'Bear Men Studio', 'barbershop', 'Barbería Masculina', 'Valparaíso', 'Av. Argentina 540', -33.0441, -71.6052, null, false, 3, null, 'https://instagram.com/bearmenstudio', null, true, false, false, false, true, '+56912345678', null, '+56912345678', 4.9, 455, 'high', false, 'Operativo verificado en directorio', 32, 23, 9, 10, 9, 83, 88, 'HIGH', '[{"dimension":"digital_need","points":22,"label":"Carencia de web propia (solo perfil en AgendaPro)"},{"dimension":"digital_need","points":10,"label":"Sin integración de reservas directa propia"},{"dimension":"commercial_attractiveness","points":10,"label":"Alto volumen de reseñas (455 reseñas, rating 4.9)"},{"dimension":"commercial_attractiveness","points":5,"label":"Rating sólido"},{"dimension":"contactability","points":9,"label":"Canal de WhatsApp/Teléfono directo activo"},{"dimension":"landing_fit","points":10,"label":"Fit perfecto para landing de barbería"},{"dimension":"local_opportunity","points":9,"label":"Oportunidad territorial en eje Av. Argentina"}]'::jsonb, array['placeholder_phone']::text[], 'agendapro', array['https://agendapro.com/mp/cl/corte-cabello-valparaiso']::text[], '2025-02-22T14:30:00Z', 'Perfil activo en AgendaPro sin sitio web propio independiente registrado.', null),
  ('b002', 'María Clarita Taquería', 'restaurant', 'Tex-Mex / Tequilería', 'Viña del Mar', 'Av. San Martín 410', -33.0182, -71.5512, 'https://mariaclarita.cl', true, 0, 'Alta responsividad, HTTPS activo, menú en HTML', 'https://instagram.com/restaurantmariaclarita', null, false, true, false, true, true, '+56322696737', 'contacto@mariaclarita.cl', '+56322696737', 4.6, 380, 'high', false, 'Operativo desde 2021', 8, 22, 15, 9, 7, 61, 95, 'GOOD', '[]'::jsonb, '{}'::text[], 'direct', array['https://mariaclarita.cl']::text[], '2025-02-22T14:30:00Z', 'Sitio propio funcional con integración de reservas.', null),
  ('b003', 'Aquí Jaime', 'restaurant', null, 'Concón', 'Av. Borgoño 21303', -32.9231, -71.5432, 'https://aquijaime.cl', true, 0, null, null, null, false, null, null, null, null, null, null, '+56322812042', null, null, null, null, null, 10, 20, 11, 9, 8, 58, 92, 'MEDIUM', '[]'::jsonb, '{}'::text[], 'direct', array['https://aquijaime.cl/']::text[], '2025-02-22T14:30:00Z', null, null),
  ('b004', 'Macho''s Barbershop', 'barbershop', 'Barbería Masculina', 'Viña del Mar', '4 Norte 477', -33.0152, -71.5488, null, false, 3, null, null, null, true, null, null, null, null, null, null, null, null, null, null, null, null, 31, 21, 8, 10, 9, 79, 82, 'HIGH', '[{"dimension":"digital_need","points":22,"label":"Operatividad exclusiva mediante Fresha"},{"dimension":"digital_need","points":9,"label":"Carencia de dominio corporativo propio"},{"dimension":"commercial_attractiveness","points":9,"label":"Alta demanda comercial en sector 4 Norte"},{"dimension":"commercial_attractiveness","points":5,"label":"Rating sobresaliente"},{"dimension":"contactability","points":8,"label":"Contacto comercial verificado"},{"dimension":"landing_fit","points":10,"label":"Fit de conversión para agendamiento directo"},{"dimension":"local_opportunity","points":9,"label":"Relevancia en polo Viña Centro"}]'::jsonb, '{}'::text[], 'fresha', array['https://www.fresha.com/es/a/machos-barbershop-vina-del-mar-vina-del-mar-4-norte-477-w61hgpyh']::text[], '2025-02-22T14:30:00Z', 'Perfil activo en Fresha sin dominio web corporativo enlazado.', null),
  ('b005', 'Barbería León Barber', 'barbershop', 'Barbería Masculina', 'Valparaíso', 'Condell 1329 local 16', -33.0478, -71.6211, null, false, 4, null, null, null, false, null, null, null, null, null, null, null, null, null, null, null, null, 35, 18, 7, 10, 8, 78, 79, 'HIGH', '[{"dimension":"digital_need","points":25,"label":"No se encontró sitio web tras búsqueda"},{"dimension":"digital_need","points":10,"label":"Ausencia de motor de agendamiento independiente"},{"dimension":"commercial_attractiveness","points":8,"label":"Flujo constante de clientes en local de Calle Condell"},{"dimension":"commercial_attractiveness","points":5,"label":"Rating altamente favorable"},{"dimension":"contactability","points":7,"label":"WhatsApp verificado"},{"dimension":"landing_fit","points":10,"label":"Fit para landing page"},{"dimension":"local_opportunity","points":8,"label":"Elevada brecha digital en cuadrante almendral"}]'::jsonb, '{}'::text[], 'agendapro', array['https://agendapro.com/mp/cl/corte-cabello-valparaiso']::text[], '2025-02-22T14:30:00Z', 'Perfil activo en AgendaPro sin dominio web corporativo enlazado.', null),
  ('b006', 'The Wolf Salon', 'barbershop', 'Barbería Premium / Salón Masculino', 'Viña del Mar', 'Centro Viña', -33.021, -71.552, 'https://www.the-wolf.cl', true, 0, null, null, null, false, null, null, null, null, null, null, null, null, null, null, null, null, 6, 21, 11, 9, 7, 54, 90, 'MEDIUM', '[]'::jsonb, '{}'::text[], 'direct', array['https://www.the-wolf.cl/']::text[], '2025-02-22T14:30:00Z', null, null),
  ('b007', 'Humano Salon Barber', 'barbershop', 'Barbería Masculina', 'Viña del Mar', 'Viña del Mar', -33.0235, -71.5541, 'https://humanosalonbarber.cl', true, 1, null, null, null, false, null, null, null, null, null, null, null, null, null, null, null, null, 18, 19, 10, 9, 8, 64, 86, 'GOOD', '[]'::jsonb, '{}'::text[], 'direct', array['https://humanosalonbarber.cl/']::text[], '2025-02-22T14:30:00Z', null, null),
  ('b008', 'Bar La Virgen Reñaca', 'bar', null, 'Viña del Mar', 'Sector Reñaca', -32.9712, -71.5491, 'https://www.barlavirgen.cl', true, 0, null, null, null, false, null, null, null, null, null, null, null, null, null, null, null, null, 9, 24, 12, 8, 8, 61, 94, 'GOOD', '[]'::jsonb, '{}'::text[], 'direct', array['https://www.barlavirgen.cl/']::text[], '2025-02-22T14:30:00Z', null, null),
  ('b009', 'La Isla Cochoa', 'restaurant', null, 'Concón', 'Av. Borgoño Cochoa', -32.9511, -71.5475, 'https://grupoisla.cl/pages/la-isla-cochoa', true, 0, null, null, null, false, null, null, null, null, null, null, null, null, null, null, null, null, 7, 23, 11, 9, 8, 58, 91, 'MEDIUM', '[]'::jsonb, '{}'::text[], 'direct', array['https://grupoisla.cl/pages/la-isla-cochoa']::text[], '2025-02-22T14:30:00Z', null, null),
  ('b010', 'Barbería Pinto', 'barbershop', 'Barbería Masculina', 'Valparaíso', 'Valparaíso Centro', -33.046, -71.618, null, false, 4, null, null, null, false, null, null, null, null, null, null, null, null, null, null, null, null, 35, 16, 6, 10, 8, 75, 74, 'HIGH', '[{"dimension":"digital_need","points":25,"label":"Sin sitio web propio detectado"},{"dimension":"digital_need","points":10,"label":"Carencia de sistema de turnos propio"},{"dimension":"commercial_attractiveness","points":7,"label":"Tracción media en zona centro"},{"dimension":"commercial_attractiveness","points":5,"label":"Rating positivo"},{"dimension":"contactability","points":6,"label":"Canal de contacto activo"},{"dimension":"landing_fit","points":10,"label":"Fit de conversión B2B"},{"dimension":"local_opportunity","points":8,"label":"Alta brecha competitiva local"}]'::jsonb, '{}'::text[], 'agendapro', array['https://agendapro.com/mp/cl/corte-cabello-valparaiso']::text[], '2025-02-22T14:30:00Z', 'Perfil activo en AgendaPro sin dominio web corporativo enlazado.', null),
  ('b011', 'Peluquería Acuña', 'barbershop', 'Barbería Masculina', 'Valparaíso', 'Eloy Alfaro 14', -33.0432, -71.6155, null, false, 4, null, null, null, false, null, null, null, null, null, null, null, null, null, null, null, null, 34, 17, 7, 10, 8, 76, 76, 'HIGH', '[{"dimension":"digital_need","points":25,"label":"Sin presencia web estructurada"},{"dimension":"digital_need","points":9,"label":"Carencia de catálogo visual de servicios"},{"dimension":"commercial_attractiveness","points":8,"label":"Actividad comercial continua en Eloy Alfaro"},{"dimension":"commercial_attractiveness","points":5,"label":"Excelente reputación local"},{"dimension":"contactability","points":7,"label":"Teléfono/WhatsApp disponible"},{"dimension":"landing_fit","points":10,"label":"Fit extremo para landing page"},{"dimension":"local_opportunity","points":8,"label":"Oportunidad en sector comercial Valparaíso"}]'::jsonb, '{}'::text[], 'agendapro', array['https://agendapro.com/mp/cl/corte-cabello-valparaiso']::text[], '2025-02-22T14:30:00Z', 'Perfil activo en AgendaPro sin dominio web corporativo enlazado.', null),
  ('b012', 'Tutti Foods', 'restaurant', null, 'Villa Alemana', 'Carlos Saavedra 33', -33.0421, -71.3722, null, false, 3, null, null, null, true, null, null, null, null, null, null, null, null, null, null, null, null, 30, 19, 8, 9, 9, 75, 80, 'HIGH', '[{"dimension":"digital_need","points":22,"label":"Operatividad concentrada en aplicaciones de delivery"},{"dimension":"digital_need","points":8,"label":"Fuga relevante de margen por comisiones de terceros"},{"dimension":"commercial_attractiveness","points":9,"label":"Volumen de pedidos continuo en Villa Alemana"},{"dimension":"commercial_attractiveness","points":5,"label":"Buena calificación"},{"dimension":"contactability","points":8,"label":"WhatsApp Business activo"},{"dimension":"landing_fit","points":9,"label":"Fit alto para menú digital transaccional"},{"dimension":"local_opportunity","points":9,"label":"Cero competencia web en su cuadrante"}]'::jsonb, '{}'::text[], 'delivery_app', array['https://www.rappi.cl/restaurantes/delivery/69931-tutti-foods-villa-alemana']::text[], '2025-02-22T14:30:00Z', 'Alta presencia en aplicaciones de despacho sin sitio web ni carta digital interactiva propia.', null),
  ('b013', 'Barbería Urban Corte y Stylo', 'barbershop', 'Barbería Masculina', 'Valparaíso', 'El Sauce 311, Placilla', -33.111, -71.543, null, false, 4, null, null, null, false, null, null, null, null, null, null, null, null, null, null, null, null, 35, 15, 6, 10, 7, 73, 72, 'GOOD', '[]'::jsonb, '{}'::text[], 'agendapro', array['https://agendapro.com/mp/cl/corte-cabello-valparaiso']::text[], '2025-02-22T14:30:00Z', 'Perfil activo en AgendaPro sin dominio web corporativo enlazado.', null),
  ('b014', 'Restaurant San Marino''s', 'restaurant', 'Puerto y Pastas', 'Viña del Mar', 'Av. Borgoño 16805', -32.962, -71.546, 'https://www.sanmarinochile.com', true, 1, null, null, null, false, null, null, null, null, null, null, null, null, null, null, null, null, 19, 20, 10, 9, 8, 66, 88, 'GOOD', '[]'::jsonb, '{}'::text[], 'direct', array['https://www.sanmarinochile.com/']::text[], '2025-02-22T14:30:00Z', null, null),
  ('b015', 'Nicole Moreno By Luli', 'boutique', 'Tienda de ropa', 'Viña del Mar', 'Centro Viña', -33.0205, -71.551, null, false, 3, null, null, null, true, null, null, null, null, null, null, null, null, null, null, null, null, 28, 18, 7, 6, 7, 66, 70, 'GOOD', '[]'::jsonb, '{}'::text[], 'social_news', array['https://www.guioteca.com/moda/nicole-luli-moreno-invita-a-conocer-su-nueva-tienda-de-ropa-exclusiva-con-seductoras-imagenes/']::text[], '2025-02-22T14:30:00Z', null, null)
on conflict (business_id) do update
set
    business_name = excluded.business_name,
    niche = excluded.niche,
    subcategory = excluded.subcategory,
    commune = excluded.commune,
    address = excluded.address,
    latitude = excluded.latitude,
    longitude = excluded.longitude,
    website_url = excluded.website_url,
    has_website = excluded.has_website,
    website_classification = excluded.website_classification,
    website_quality = excluded.website_quality,
    instagram_url = excluded.instagram_url,
    facebook_url = excluded.facebook_url,
    social_only_presence = excluded.social_only_presence,
    online_booking = excluded.online_booking,
    online_ordering = excluded.online_ordering,
    online_menu = excluded.online_menu,
    online_catalog = excluded.online_catalog,
    whatsapp_business = excluded.whatsapp_business,
    public_business_email = excluded.public_business_email,
    public_business_phone = excluded.public_business_phone,
    rating = excluded.rating,
    review_count = excluded.review_count,
    social_activity = excluded.social_activity,
    multiple_locations = excluded.multiple_locations,
    business_age_signal = excluded.business_age_signal,
    digital_need_score = excluded.digital_need_score,
    commercial_attractiveness_score = excluded.commercial_attractiveness_score,
    contactability_score = excluded.contactability_score,
    landing_fit_score = excluded.landing_fit_score,
    local_opportunity_score = excluded.local_opportunity_score,
    priority_score = excluded.priority_score,
    confidence_score = excluded.confidence_score,
    priority_tier = excluded.priority_tier,
    score_explanations = excluded.score_explanations,
    data_flags = excluded.data_flags,
    source_primary = excluded.source_primary,
    source_urls = excluded.source_urls,
    retrieved_at = excluded.retrieved_at,
    evidence_notes = excluded.evidence_notes,
    demo_url = excluded.demo_url;
